steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_BASE_URL=https://bloom-backend-683608585705.europe-west1.run.app'
      - '--build-arg'
      - 'VITE_GOOGLE_CLIENT_ID=683608585705-9322d8jjtek6dgt8pfbojgg9pdsvf7fe.apps.googleusercontent.com'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY'
      - '-t'
      - 'europe-west1-docker.pkg.dev/bloom-today/cloud-run-source-deploy/bloom/bloom-frontend:$SHORT_SHA'
      - '-t'
      - 'europe-west1-docker.pkg.dev/bloom-today/cloud-run-source-deploy/bloom/bloom-frontend:latest'
      - '-f'
      - '/workspace/frontend/Dockerfile'
      - '/workspace/frontend'

    secretEnv:
      - 'VITE_GEMINI_API_KEY'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/bloom-today/cloud-run-source-deploy/bloom/bloom-frontend:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'bloom-frontend'
      - '--image=europe-west1-docker.pkg.dev/bloom-today/cloud-run-source-deploy/bloom/bloom-frontend:$SHORT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: 'projects/bloom-today/secrets/VITE_GEMINI_API_KEY/versions/latest'
      env: 'VITE_GEMINI_API_KEY'

images:
  - 'europe-west1-docker.pkg.dev/bloom-today/cloud-run-source-deploy/bloom/bloom-frontend:$SHORT_SHA'
  - 'europe-west1-docker.pkg.dev/bloom-today/cloud-run-source-deploy/bloom/bloom-frontend:latest'
