export const talkingHeadAvatarPresets = {
  brunette: {
    id: 'brunette',
    label: 'Brunette',
    url: '/talkinghead/avatars/brunette.glb',
    body: 'F',
    avatarMood: 'neutral',
  },
  mpfb: {
    id: 'mpfb',
    label: 'MPFB',
    url: '/talkinghead/avatars/mpfb.glb',
    body: 'F',
    avatarMood: 'happy',
    modelDynamicBones: [
      {
        bone: 'LeftBreast',
        type: 'point',
        stiffness: 600,
        damping: 20,
        deltaLocal: [0, 0.01, 0],
        deltaWorld: [0, -0.02, 0],
        limits: [[-0.02, 0.02], [-0.02, 0.06], [-0.02, 0.02], [-0.5, 0.5]],
      },
      {
        bone: 'RightBreast',
        type: 'point',
        stiffness: 600,
        damping: 20,
        deltaLocal: [0, 0.01, 0],
        deltaWorld: [0, -0.02, 0],
        limits: [[-0.02, 0.02], [-0.02, 0.06], [-0.02, 0.02], [-0.5, 0.5]],
      },
      {
        bone: 'Ponytail1',
        type: 'mix2',
        stiffness: 100,
        damping: 4,
        limits: [null, null, [null, 0.02], null],
        pivot: true,
      },
      {
        bone: 'Ponytail2',
        type: 'mix2',
        stiffness: 150,
        damping: 4,
        limits: [null, null, [null, 0.01], null],
      },
      {
        bone: 'Ponytail3',
        type: 'mix2',
        stiffness: 200,
        damping: 4,
        limits: [null, null, [null, 0.01], null],
      },
    ],
    baseline: {
      headRotateX: -0.01,
      eyeBlinkLeft: 0.05,
      eyeBlinkRight: 0.05,
    },
  },
  avaturn: {
    id: 'avaturn',
    label: 'Avaturn',
    url: '/talkinghead/avatars/avaturn.glb',
    body: 'F',
    avatarMood: 'happy',
    retarget: {
      Hips: { y: 0.03 },
      Spine: { y: 0.02 },
      Spine1: { y: 0.02, z: 0.01 },
      Spine2: { y: 0.02, z: 0.01 },
      Neck: { z: 0.02, y: 0.01 },
      Head: { z: 0.02 },
      LeftShoulder: { rx: -0.5 },
      RightShoulder: { rx: -0.5 },
      scaleToHipsLevel: 1.0,
    },
    baseline: {
      headRotateX: -0.05,
      eyeBlinkLeft: 0.15,
      eyeBlinkRight: 0.15,
    },
  },
  avatarsdk: {
    id: 'avatarsdk',
    label: 'AvatarSDK',
    url: '/talkinghead/avatars/avatarsdk.glb',
    body: 'M',
    avatarMood: 'neutral',
    retarget: {
      Neck: { z: -0.01, rx: -0.15 },
      Neck1: { z: -0.01, rx: -0.15 },
      Neck2: { z: -0.01, rx: -0.15 },
      LeftShoulder: { rz: -0.3 },
      RightShoulder: { rz: 0.3 },
      scaleToEyesLevel: 1.0,
      origin: { y: -0.1 },
    },
    baseline: {
      headRotateX: -0.04,
      eyeBlinkLeft: 0.05,
      eyeBlinkRight: 0.05,
    },
  },
};

export const talkingHeadAvatarOptions = Object.values(talkingHeadAvatarPresets);
